Changes rubric headers to sentence case
crate/getting-started pull request #58
Opened 2019-06-11 10:49 UTC by kevinkq

## Summary of the changes / Why this is an improvement

This pr changes the rubric headers from title case to sentence case and thereby completes the initial iteration of changes to headers and titles.

## Checklist

 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed

2019-06-14 13:14 UTC, nomicode requested changes

2019-06-14 13:14 UTC, mechanomi commented on docs/first-use/query.txt
> +The CrateDB shell
"CrateDB Shell" is a proper noun

2019-06-18 07:16 UTC, kevinkq commented on docs/first-use/query.txt
> +The CrateDB shell
This typo was already fixed.

2019-06-19 12:53 UTC, nomicode approved these changes
please squash your changes and fix the commit message before merging

2019-06-21 12:59 UTC, merged